services:

  # ne depend pas des autres
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env

  # depend de mariadb
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb

  # depend de wordpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports: # Redirige le port 443 de l'host vers le port 443 du conteneur
      - '443:443'
    volumes:
      - wordpress_files:/var/www/inception/
    networks: 
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vtestut/data/database


  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vtestut/data/wordpress_files

networks:
  all:
    driver: bridge # permet au conteneur communiquer entre eux via des adresses IP privées tout en étant isolés du reste du réseau.
